ALTER TABLE Cliente 
    ADD CONSTRAINT Num_CliCPFCNPJ VARCHAR(14) 
	PRIMARY KEY IDENTITY(1,1);

ALTER TABLE Status 
    ADD CONSTRAINT Cod_StatusContVend INT 
    PRIMARY KEY IDENTITY(1,1);

<<<<<<< HEAD
ALTER TABLE Empreendimento 
    ADD CONSTRAINT Num_Empr SMALLINT
    PRIMARY KEY NOT NULL UNIQUE (Num_Empr); 

ALTER TABLE Baixa
    ADD CONSTRAINT Cod_TipoBaiPar
    TINYINT PRIMARY KEY NOT NULL UNIQUE (Cod_TipoBaiPar);
=======
ALTER TABLE BaixaParcela
    ADD CONSTRAINT Cod_TipBaiPar INT 
	PRIMARY KEY IDENTITY(1,1);
>>>>>>> 38f0b0dc685c0c006ae3cfddcd9f82a9f009e981

ALTER TABLE TipoParcela 
    ADD CONSTRAINT Cod_TipParc INT
	PRIMARY KEY IDENTITY(1,1);

ALTER TABLE Lote 
    ADD CONSTRAINT Num_Chavlot INT 
    PRIMARY KEY IDENTITY(1,1);

ALTER TABLE Contrato 
    ADD CONSTRAINT Num_Contr INT 
    PRIMARY KEY IDENTITY(1,1);

ALTER TABLE Parcela 
    ADD CONSTRAINT Num_ChavParc INT 
	PRIMARY KEY IDENTITY(1,1);

------------------------------
ALTER TABLE Contrato
ADD FK_Num_ChavLot INT
CONSTRAINT Fk_Num_ChavLot FOREIGN KEY (FK_Num_ChavLot)
REFERENCES Lote (Num_ChavLot)

ALTER TABLE Contrato
ADD FK_Cod_StatusContVend INT
CONSTRAINT FK_Cod_StatusContVend FOREIGN KEY (FK_Cod_StatusContVend)
REFERENCES Status (Cod_StatusContVend)

ALTER TABLE Contrato
ADD Num_CliCPFCNPJ INT
CONSTRAINT Fk_Num_CliCPFCNPJ FOREIGN KEY (Num_CliCPFCNPJ)
REFERENCES Cliente (Num_CliCPFCNPJ) 

------------------------------------------
ALTER TABLE Parcela
ADD Cod_TipParc INT
CONSTRAINT Fk_Cod_TipParc FOREIGN KEY (Cod_TipParc)
REFERENCES TipoParcela (Cod_TipParc)

ALTER TABLE Parcela
ADD Cod_TipBaiParc INT
CONSTRAINT Fk_Cod_TipBaiParc FOREIGN KEY (Cod_TipBaiParc)
REFERENCES BaixaParcela (Cod_TipBaiParc)

ALTER TABLE Parcela
ADD Num_Contr INT
CONSTRAINT Fk_Num_Contr FOREIGN KEY (Num_Contr)
REFERENCES Contrato (Num_Contr)